/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentManager from "@strapi/content-manager/strapi-admin";
import contentTypeBuilder from "@strapi/content-type-builder/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import upload from "@strapi/upload/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-manager": contentManager,
    "content-type-builder": contentTypeBuilder,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    upload: upload,
  },
});
